// Generated by scripts/generate-l10n.sh — DO NOT EDIT MANUALLY
import Foundation

// MARK: - L10n

/// CoreUI バンドル内の Localizable.xcstrings からローカライズ文字列を提供する。
///
/// プロパティ名は Xcode が String Catalog から生成するシンボル名規則（ドット除去のキャメルケース）に準拠する。
/// 例: キー `cityList.title` → `L10n.cityListTitle`
///
/// View 側は `Text(L10n.cityListTitle)` のように使用する。
public enum L10n {
    public static var cityListTitle: String {
        String(localized: "cityList.title", bundle: Bundle.module)
    }

    public static var citySearchEmptyResult: String {
        String(localized: "citySearch.emptyResult", bundle: Bundle.module)
    }

    public static var citySearchSearchPrompt: String {
        String(localized: "citySearch.searchPrompt", bundle: Bundle.module)
    }

    public static var citySearchTitle: String {
        String(localized: "citySearch.title", bundle: Bundle.module)
    }

    public static var currentWeatherAccessibilityFeelsLikeFormat: String {
        String(localized: "currentWeather.accessibility.feelsLikeFormat", bundle: Bundle.module)
    }

    public static var currentWeatherAccessibilityHumidityFormat: String {
        String(localized: "currentWeather.accessibility.humidityFormat", bundle: Bundle.module)
    }

    public static var currentWeatherAccessibilityWindFormat: String {
        String(localized: "currentWeather.accessibility.windFormat", bundle: Bundle.module)
    }

    public static var currentWeatherFeelsLikePrefix: String {
        String(localized: "currentWeather.feelsLikePrefix", bundle: Bundle.module)
    }

    public static var currentWeatherHourlyChartButton: String {
        String(localized: "currentWeather.hourlyChartButton", bundle: Bundle.module)
    }

    public static var currentWeatherLoading: String {
        String(localized: "currentWeather.loading", bundle: Bundle.module)
    }

    public static var currentWeatherOpenSettings: String {
        String(localized: "currentWeather.openSettings", bundle: Bundle.module)
    }

    public static var currentWeatherRetry: String {
        String(localized: "currentWeather.retry", bundle: Bundle.module)
    }

    public static var currentWeatherTitle: String {
        String(localized: "currentWeather.title", bundle: Bundle.module)
    }

    public static var currentWeatherTodayForecast: String {
        String(localized: "currentWeather.todayForecast", bundle: Bundle.module)
    }

    public static var currentWeatherWeeklyForecastButton: String {
        String(localized: "currentWeather.weeklyForecastButton", bundle: Bundle.module)
    }

    public static var hourlyChartAxisTitleFormat: String {
        String(localized: "hourlyChart.axisTitleFormat", bundle: Bundle.module)
    }

    public static var hourlyChartDataPointLabelFormat: String {
        String(localized: "hourlyChart.dataPointLabelFormat", bundle: Bundle.module)
    }

    public static var hourlyChartPrecipitation: String {
        String(localized: "hourlyChart.precipitation", bundle: Bundle.module)
    }

    public static var hourlyChartPrecipitationSummaryFormat: String {
        String(localized: "hourlyChart.precipitationSummaryFormat", bundle: Bundle.module)
    }

    public static var hourlyChartPrecipitationUnitName: String {
        String(localized: "hourlyChart.precipitationUnitName", bundle: Bundle.module)
    }

    public static var hourlyChartTemperature: String {
        String(localized: "hourlyChart.temperature", bundle: Bundle.module)
    }

    public static var hourlyChartTemperatureSummaryFormat: String {
        String(localized: "hourlyChart.temperatureSummaryFormat", bundle: Bundle.module)
    }

    public static var hourlyChartTime: String {
        String(localized: "hourlyChart.time", bundle: Bundle.module)
    }

    public static var hourlyChartTitle: String {
        String(localized: "hourlyChart.title", bundle: Bundle.module)
    }

    public static var hourlyItemAccessibilityLabelFormat: String {
        String(localized: "hourlyItem.accessibilityLabelFormat", bundle: Bundle.module)
    }

    public static var settingsApiLabel: String {
        String(localized: "settings.apiLabel", bundle: Bundle.module)
    }

    public static var settingsAppearanceSection: String {
        String(localized: "settings.appearanceSection", bundle: Bundle.module)
    }

    public static var settingsInfoSection: String {
        String(localized: "settings.infoSection", bundle: Bundle.module)
    }

    public static var settingsTemperaturePicker: String {
        String(localized: "settings.temperaturePicker", bundle: Bundle.module)
    }

    public static var settingsThemePicker: String {
        String(localized: "settings.themePicker", bundle: Bundle.module)
    }

    public static var settingsTitle: String {
        String(localized: "settings.title", bundle: Bundle.module)
    }

    public static var settingsUnitSection: String {
        String(localized: "settings.unitSection", bundle: Bundle.module)
    }

    public static var settingsWindPicker: String {
        String(localized: "settings.windPicker", bundle: Bundle.module)
    }

    public static var tabCity: String {
        String(localized: "tab.city", bundle: Bundle.module)
    }

    public static var tabSettings: String {
        String(localized: "tab.settings", bundle: Bundle.module)
    }

    public static var tabWeather: String {
        String(localized: "tab.weather", bundle: Bundle.module)
    }

    public static var temperatureUnitCelsiusAccessibility: String {
        String(localized: "temperatureUnit.celsius.accessibility", bundle: Bundle.module)
    }

    public static var temperatureUnitFahrenheitAccessibility: String {
        String(localized: "temperatureUnit.fahrenheit.accessibility", bundle: Bundle.module)
    }

    public static var themeDark: String {
        String(localized: "theme.dark", bundle: Bundle.module)
    }

    public static var themeLight: String {
        String(localized: "theme.light", bundle: Bundle.module)
    }

    public static var themeSystem: String {
        String(localized: "theme.system", bundle: Bundle.module)
    }

    public static var weeklyForecastTitle: String {
        String(localized: "weeklyForecast.title", bundle: Bundle.module)
    }

    public static var windUnitKmhAccessibility: String {
        String(localized: "windUnit.kmh.accessibility", bundle: Bundle.module)
    }

    public static var windUnitMphAccessibility: String {
        String(localized: "windUnit.mph.accessibility", bundle: Bundle.module)
    }
}
