// Generated by scripts/generate-l10n.sh — DO NOT EDIT MANUALLY
import Foundation

// MARK: - L10n

/// CoreUI バンドル内の Localizable.xcstrings からローカライズ文字列を提供する。
///
/// プロパティ名は Xcode が String Catalog から生成するシンボル名規則（ドット除去のキャメルケース）に準拠する。
/// 例: キー `cityList.title` → `L10n.cityListTitle`
///
/// View 側は `Text(L10n.cityListTitle)` のように使用する。
public enum L10n {
    public static var cityListTitle: String {
        String(localized: "cityList.title", bundle: Bundle.module)
    }
    public static var citySearchEmptyResult: String {
        String(localized: "citySearch.emptyResult", bundle: Bundle.module)
    }
    public static var citySearchSearchPrompt: String {
        String(localized: "citySearch.searchPrompt", bundle: Bundle.module)
    }
    public static var citySearchTitle: String {
        String(localized: "citySearch.title", bundle: Bundle.module)
    }
    public static var currentWeatherFeelsLikePrefix: String {
        String(localized: "currentWeather.feelsLikePrefix", bundle: Bundle.module)
    }
    public static var currentWeatherHourlyChartButton: String {
        String(localized: "currentWeather.hourlyChartButton", bundle: Bundle.module)
    }
    public static var currentWeatherLoading: String {
        String(localized: "currentWeather.loading", bundle: Bundle.module)
    }
    public static var currentWeatherOpenSettings: String {
        String(localized: "currentWeather.openSettings", bundle: Bundle.module)
    }
    public static var currentWeatherRetry: String {
        String(localized: "currentWeather.retry", bundle: Bundle.module)
    }
    public static var currentWeatherTitle: String {
        String(localized: "currentWeather.title", bundle: Bundle.module)
    }
    public static var currentWeatherTodayForecast: String {
        String(localized: "currentWeather.todayForecast", bundle: Bundle.module)
    }
    public static var currentWeatherWeeklyForecastButton: String {
        String(localized: "currentWeather.weeklyForecastButton", bundle: Bundle.module)
    }
    public static var hourlyChartPrecipitation: String {
        String(localized: "hourlyChart.precipitation", bundle: Bundle.module)
    }
    public static var hourlyChartTemperature: String {
        String(localized: "hourlyChart.temperature", bundle: Bundle.module)
    }
    public static var hourlyChartTime: String {
        String(localized: "hourlyChart.time", bundle: Bundle.module)
    }
    public static var hourlyChartTitle: String {
        String(localized: "hourlyChart.title", bundle: Bundle.module)
    }
    public static var settingsAppearanceSection: String {
        String(localized: "settings.appearanceSection", bundle: Bundle.module)
    }
    public static var settingsInfoSection: String {
        String(localized: "settings.infoSection", bundle: Bundle.module)
    }
    public static var settingsTemperaturePicker: String {
        String(localized: "settings.temperaturePicker", bundle: Bundle.module)
    }
    public static var settingsThemePicker: String {
        String(localized: "settings.themePicker", bundle: Bundle.module)
    }
    public static var settingsTitle: String {
        String(localized: "settings.title", bundle: Bundle.module)
    }
    public static var settingsUnitSection: String {
        String(localized: "settings.unitSection", bundle: Bundle.module)
    }
    public static var settingsWindPicker: String {
        String(localized: "settings.windPicker", bundle: Bundle.module)
    }
    public static var tabCity: String {
        String(localized: "tab.city", bundle: Bundle.module)
    }
    public static var tabSettings: String {
        String(localized: "tab.settings", bundle: Bundle.module)
    }
    public static var tabWeather: String {
        String(localized: "tab.weather", bundle: Bundle.module)
    }
    public static var weeklyForecastTitle: String {
        String(localized: "weeklyForecast.title", bundle: Bundle.module)
    }
}
