#!/usr/bin/env python3
"""Generate L10n.swift from Localizable.xcstrings.

Usage: python3 scripts/generate-l10n.py <xcstrings> <output>
"""

import json
import sys


def to_camel_case(key: str) -> str:
    """Convert dot-separated key to camelCase. e.g. tab.weather -> tabWeather"""
    parts = key.split(".")
    return parts[0] + "".join(p[0].upper() + p[1:] for p in parts[1:])


def generate(xcstrings_path: str, output_path: str) -> None:
    with open(xcstrings_path, encoding="utf-8") as f:
        data = json.load(f)

    keys = sorted(data.get("strings", {}).keys())

    lines = [
        "// Generated by scripts/generate-l10n.sh — DO NOT EDIT MANUALLY",
        "import Foundation",
        "",
        "// MARK: - L10n",
        "",
        "/// CoreUI バンドル内の Localizable.xcstrings からローカライズ文字列を提供する。",
        "///",
        "/// プロパティ名は Xcode が String Catalog から生成するシンボル名規則（ドット除去のキャメルケース）に準拠する。",
        "/// 例: キー `cityList.title` → `L10n.cityListTitle`",
        "///",
        "/// View 側は `Text(L10n.cityListTitle)` のように使用する。",
        "public enum L10n {",
    ]

    for key in keys:
        prop = to_camel_case(key)
        lines.append(f'    public static var {prop}: String {{')
        lines.append(f'        String(localized: "{key}", bundle: Bundle.module)')
        lines.append(f'    }}')

    lines.append("}")
    lines.append("")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Generated {len(keys)} keys → {output_path}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <xcstrings> <output>", file=sys.stderr)
        sys.exit(1)
    generate(sys.argv[1], sys.argv[2])
